version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - shortenurl-network
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - shortenurl-network
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      replicas: 1

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - shortenurl-network
    deploy:
      replicas: 1

  shortenurl:
    image: shortenurl-image
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - shortenurl-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"

  mysql:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortenurl
    ports:
      - "3306:3306"
    networks:
      - shortenurl-network
    deploy:
      replicas: 1

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    networks:
      - shortenurl-network
    volumes:
      - influxdb_data:/var/lib/influxdb
    deploy:
      replicas: 1

networks:
  shortenurl-network:
    driver: overlay

volumes:
  influxdb_data:
